project:
  type: website
  output-dir: docs
  resources:
    - akrun.mp4

website:
  title: "akrun Analytics | Elevating businesses into Singularity"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      #- testing.qmd
      #- hobbies.qmd
      - vision.qmd
      - reviews.qmd

format:
  html: 
    title: "akrun Analytics | Elevating businesses into Singularity"
    theme: 
     dark: slate
     light: minty
    css: styles.css
    page-layout: full
    
editor: visual

