project:
  type: website
  output-dir: docs

website:
  title: "akrunanalyticscorp"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - hobbies.qmd

format:
  html:
    theme: 
     dark: slate
     light: minty
    css: styles.css

editor: visual

