project:
  type: website
  output-dir: docs
  render:
    - /index.qmd
    - /about.qmd
    - /vision.qmd
    - /reviews.qmd
    - /Hello_world.qmd
  resources:
    - akrun.mp4

website:
  title: "akrun Analytics | Elevating businesses into Singularity"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      #- testing.qmd
      #- hobbies.qmd
      - vision.qmd
      - reviews.qmd
      - Hello_world.qmd

format:
  html: 
    title: "akrun Analytics | Elevating businesses into Singularity"
    theme: 
     dark: slate
     light: minty
    css: styles.css
    page-layout: full
    toc: true
    
editor: visual

